- src/websocket.rs
Pulls out `websocket::serve` logic into a `WebsocketServer` trait allowing more control over the session flow (necessary for how the early plugins api will work.)
> refactor(ws): make the websocket logic more generic/hookable

- ui/src/Components/Sidebar/General.jsx
- ui/src/Components/Sidebar/Index.jsx
- ui/src/Components/Sidebar/Index.scss
- ui/src/Components/Sidebar/Libraries.jsx
Decision for putting it in the bottom: looks bad when it's above and not in active state. Plus, preferences doesn't look too lonely since logout button has been moved inside it.
I guess also, priorities, at the end of the day, libraries I'd say take priority over dashboard which is the first thing people visit anyway by default.
> Move sidebar dashboard item

- ui/public/index.html
- ui/src/App.jsx
- ui/src/Components/Banners/Banner.jsx
- ui/src/Components/Banners/Banner.scss
- ui/src/Components/Banners/Crumbs.scss
- ui/src/Components/Banners/Image.jsx
- ui/src/Components/Banners/Index.scss
- ui/src/Components/Banners/ProgressBar.scss
- ui/src/Components/CardList/Card.scss
- ui/src/Components/CardList/Image.jsx
- ui/src/Components/CardList/Index.jsx
- ui/src/Components/ImageLoad.jsx
- ui/src/Components/Sidebar/Index.jsx
- ui/src/Components/Sidebar/Libraries.jsx
- ui/src/Pages/Media/Banner.scss
- ui/src/Pages/Media/BannerImage.jsx
- ui/src/Pages/Media/CardImage.jsx
- ui/src/Pages/Media/Index.scss
- ui/src/Themes/Blind.js
- ui/src/Themes/Default.js
- ui/src/Themes/LightsOff.js
All images across Dim _should_ now:
Other changes
- Fixes libraries section in sidebar not showing when adding new library for the first time
- Theme and favicon should now work even if server is offline because they were housed under the WS component
- Tweaks to banner colors
> Refactor image loading

- README.md
This library is required for the bundled FFMPEG, but it is not always included by default by the OS. An example is `images:ubuntu/focal` on LXD, it does not include libtheora0
> Added library libtheora0 to the list of required libraries. 

- ui/src/Pages/VideoPlayer/Index.jsx
The video player page wasn't loading for me because the code assumed that at least one of the tracks would be marked with `is_default`, which apparently isn't always true. This change selects the first track if none are marked with `is_default`.
> Pick the first video track if none are marked as default.

- ui/src/Components/Card/Image.jsx
Fixes a memory leak in the CardImage component:
> Clean up IntersectionObserver when CardImage is unmounted.

- Dockerfile
- README.md
- dim/Cargo.toml
- ui/package.json
I wasn't able to build dim on macOS because libva isn't available. I was able to get it to build by making nightfall's vaapi feature off by default. I updated the Dockerfile so that the image builds with the vaapi feature, since it's available there. I also found that I needed to make `ffmpeg` and `ffprobe` available in the `utils` directory relative to the root of the repository for the server to run.
I cleaned up the README to make the installation and build instructions more clear.
Up until now I'd been running the server using the pre-built Docker image. For some reason, when running it locally, the proxy that the React app uses to forward WebSocket requests from port 3000 to port 8000 didn't work using "localhost" but did work using 127.0.0.1. I'm not sure why, but it works both ways …
> Support building on macOS and improve setup instructions.

- dim/src/errors.rs
- dim/src/routes/auth.rs
- dim/src/routes/mod.rs
There was some duplication and confusing overlap in `DimError` and `AuthError` (and at least one case where a confusing HTTP status code was used—see #370), so I thought it made sense to fold `AuthError`'s variants into `DimError`.
Notable changes:
* `AuthRequired` variant renamed to `Unauthenticated` to distinguish more clearly from `Unauthorized`.
* `InvalidCredentials` variant used for all places where a login/password combination weren't valid. This avoids giving the user information to distinguish a bad password and a user not existing, which could be used for evil by a malicious user.
> Consolidate AuthError into DimError.

- ui/tsconfig.json
Setting this option in `tsconfig.json` allows modules to import other modules without using `../` to walk the directory tree. For example, in `src/Components/Sidebar/Index.tsx`:
```ts
import { useAppDispatch } from "../../hooks/store";
```
can now be changed to:
```ts
import { useAppDispatch } from "hooks/store";
```
This is easier to read and doesn't need to be modified if the file that is doing the import is moved to another place in the tree.
Imports beginning with `./` can and should still be used to import something deeper in the tree than the module doing the import. For example, in `src/Components/Sidebar/Index.tsx`, this import should remain as it is:
```ts
import Profile from "./Profile/Index";
```
> Set baseUrl to allow absolute imports.

- dim/src/main.rs
- dim/src/routes/settings.rs
- dim/src/streaming/mod.rs
- dim/src/utils.rs
It's not a huge issue, but I think it is possible to waste memory after repeated changes to global settings.
> Change ffpath to return String to avoid leaking memory

- ui/src/Pages/VideoPlayer/Controls/Actions/Volume.jsx
This adds a wheel event listener to the document when the video player loads. Scrolling up increases the player volume, and scrolling down decreases it.
> add event listener for wheel events

- ui/src/Pages/Dashboard/Banners/Image.tsx
- ui/src/Pages/VideoPlayer/Context.ts
- ui/src/Pages/VideoPlayer/Controls/Actions/PlayPause.jsx
- ui/src/Pages/VideoPlayer/Controls/Actions/Volume.jsx
- ui/src/Pages/VideoPlayer/Controls/SeekBar.jsx
- ui/src/Pages/VideoPlayer/Controls/SeekingTo.jsx
- ui/src/Pages/VideoPlayer/Events.jsx
- ui/src/Pages/VideoPlayer/Index.jsx
- ui/src/Pages/VideoPlayer/Menus/Settings.jsx
The `MediaPlayer` instance obtained from dash.js was being saved in our redux store but the instance isn't serialazible. This PR fixes this issue by sharing the `MediaPlayer` instance through `VIdeoPlayerContext` instead of the redux store.
This PR also fixes a TS error where `ImageLoad` would return `undefined` when there's no loading error but the URL is also null.
> Fix runtime error regarding player context

- ui/src/Pages/VideoPlayer/SsaSubtitles.jsx
This PR fixes two bugs.
1. SubtitleOctopus wouldnt get disposed when changing videos.
2. SubtitleOctopus wouldnt get disposed when switching subtitles off.
> dispose of octopus when changing videos or when turning subtitles off

- ui/src/Helpers/utils.ts
* Adds type annotations.
* Replaces the deprecated `String.prototype.substr` with `String.prototype.substring`.
* Fixes a bug where `newHeight` was not being considered when calculating a new width/height ratio for an element.
> Convert Helpers/utils to TypeScript.

- ui/src/Components/Sidebar/Index.scss
- ui/src/Components/Sidebar/Profile/Username.scss
- ui/src/Pages/Media/Dropdown.scss
- ui/src/Pages/Media/MetaContent.scss
- ui/src/Pages/VideoPlayer/Controls/Actions/Fullscreen.jsx
- ui/src/setupProxy.js
This PR fixes the following bugs:
> Fix some UI bugs

- ui/package.json
- ui/src/Components/Sidebar/Library.tsx
- ui/src/Components/Sidebar/Toggle.tsx
- ui/src/Controllers/Theme.tsx
- ui/src/Modals/ConfirmationBox.tsx
- ui/src/Modals/Index.tsx
- ui/src/Modals/InputConfirmationBox.tsx
- ui/src/Modals/SelectMediaFile/Activators/PlayButton.tsx
- ui/src/Modals/SelectMediaFile/Context.js
- ui/src/Modals/SelectMediaFile/Context.ts
- ui/src/Pages/Auth/LoginBtn.tsx
There are a bunch of JS modules with five imports, so I'll split them up into multiple PRs to make them easier to review.
The following modules are converted here:
* `Components/Sidebar/Library`
* `Components/Sidebar/Toggle`
* `Controllers/Theme`
* `Modals/Index`
* `Modals/Modals/SelectMediaFile/Context`
* `Modals/SelectMediaFile/Activators/PlayButton`
* `Pages/Auth/LoginBtn`
The following two modules also had to change due to our use of `React.cloneElement` in `Modals/Index`, which requires a different type for `children` than the one used by `React.PropsWithChildren`:
* `Modals/ConfirmationBox`
* `Modals/InputConfirmationBox`
> Convert JS modules with five imports to TS.

- .gitignore
- avoid conflict for MacOS developers
- anytime you open the project folder ("dim"), it may change the .DS_Store file
> Added .DS_Store to .gitignore file

- ui/package.json
Fixes #428 
The underlying issue was sub-dependencies  pulling in React 18, which would mess up imports.
This fixes it by limiting react in all dependencies to be `^17.0.30` (Which is what is currently used by Dim.
As an aside, if `yarn.lock` was included in the repository, this issue would have been much easier to reproduce. (package-lock.json is included, but I guess Dim used npm in the past).
> Fix Typescript compilation issue

- ui/src/Components/Card/HoverCard.jsx
Resolve TypeError: Cannot assign to read only property 'length' of object '[object Array]' error
> fix: Component Card/HoverCard.jsx  assign to read only property

- dim/src/routes/statik.rs
Trying to debug the UI in Firefox or Chrome DevTools currently shows minified JS and this error message in the console:
In place of the source maps, the backend was serving `index.html`.
This pull requests resolves that issue by serving `.map` files along with the compiled `.js` files taking the debugging experience from this:
to this:
> Serve Source Maps

- ui/package.json
- ui/src/Pages/VideoPlayer/SsaSubtitles.jsx
> Point libass-wasm dep to @jellyfin/libass-wasm instead of github.

- LICENSE.md
- dim/Cargo.toml
This PR changes the license of dim from GPLv2 to AGPLv3 (#362). The AGPLv3 license is more appropriate for a project like Dim. The new license will offer stronger guarantees compared to GPLv2, specifically in regards to network distribution.
cc: @eraychumak @mental32 @jimmycuadra @N-give @MrTimscampi @IGI-111 @sadstan @ldobbelsteen @BeardedNerd92 @d-volution @IntrepidPig @nooobcoder @rich-murphey @florimondmanca @cobyge @TobiasDeBruijn @dessalines 
I've CCd all the contributors as a heads up. If you have any concerns about this license change, please reply to this PR. If there are no concerns I'm hoping to get this merged in within the next couple of weeks.
p.s. I hope 2-3 weeks is a good enough grace period for all the contributors to see this notice.
closes: #229 and #362
> Change the license for dim from GPLv2 to AGPLv3

- README.md
Current readme still says dim is licenced under GPLv2.
This commit changes it to follow the new licence, AGPLv3.
> Update README.md to align with new licence

- dim/Cargo.toml
- dim/src/routes/statik.rs
This PR adds a feature where when requesting a image asset, a client can attach the `attach_accents=true` URI param, which will hint the backend to compute the accent colors of the image being requested. These colors are then converted to hex, concatenated with `,` as a delimiter and injected as a header into the response. The header is `x-image-accents`.
In the future it would be a good idea to cache the accents in memory.
> feature: allow clients to request dim to compute and attach accent colors

- dim/Cargo.toml
- dim/src/external/mod.rs
- dim/src/external/tmdb/cache_control.rs
- dim/src/external/tmdb/metadata_provider.rs
- dim/src/external/tmdb/mod.rs
- dim/src/external/tmdb/raw_client.rs
`TMDBMetadataProvider` is the main type used to provide a centralized store of the response-cache, the shared reqwest Client type, and the API key.
`TMDBMetadataProvider` does not implement `ExternalQuery` or `ExternalQueryShow` since it is a unified cache and so the media type being searched for must be provided explicitly.
However since the `ExternalQuery` trait does not allow passing this in the method arguments we have another type `MetadataProviderOf<K>` which is used to parameterise the search type.  `TMDBMetadataProvider::movies` and `TMDBMetadataProvider::tv_shows` will each produce `MetadataProviderOf<Movies>` and `MetadataProviderOf<TvShows>` respectively. and these are the types for which `ExternalQuery` is implemented on.
This is a private type that is the API wrapper for the …
> feat(tmdb): new tmdb client with request coalescing

- dim/src/routes/auth.rs
- ui/src/actions/auth.js
Fix bug where the invite token input wasn't showing up due to the route being renamed from /api/v1/auth/admin_exists -> /api/v1/host/admin_exists.
And remove the old /api/v1/auth/admin_exists route that seem to be unused.
> Fix invite token input not showing up when creating a new account

- Cargo.lock
- database/migrations/20220924000853_propagate-delete-assets.sql
- database/src/library.rs
- database/src/media.rs
- dim/Cargo.toml
- dim/src/core.rs
- dim/src/events/mod.rs
- dim/src/external/tmdb/cache_control.rs
- dim/src/fetcher.rs
- dim/src/lib.rs
- dim/src/main.rs
- dim/src/reactor/handler/error.rs
- dim/src/reactor/handler/mod.rs
- dim/src/reactor/mod.rs
- dim/src/reactor/types.rs
- dim/src/routes/library.rs
- dim/src/routes/statik.rs
- dim/src/scanner/mod.rs
This PR extends #447.
This PR implements a CDC pipeline for sqlite3 allowing us to decouple event sending from the scanners to simplify a lot of the logic. At the moment the CDC pipeline handles the sending of `LibraryCreated`, `LibraryDeleted`, `MediaCreated` and `MediaDeleted` websocket events. In addition it listens to changes on the `assets` table and when an asset is inserted, it is forwarded to the asset fetcher so that the assets get cached locally.
In the future this pipeline could be used for sending more granular events which contain changes to matched media objects, such as description changed, title changed, poster changed, etc. Or it could simply be reused to signal to clients that new data is available and that they should refetch.
This PR doesnt implement `MediafileMatched` …
> Add sqlite cdc event pipeline

- ui/src/Components/Card/HoverCard.scss
- ui/src/Components/Card/Index.scss
- ui/src/Pages/Media/MetaContent.scss
The titles in the dashboard did not allowed long titles to be shortened and hidden, this meant that if a title was to be long in size it went past the width of the card and unto the next card on the right.
In this PR I've fixed this problem and now it allows the titles to be hidden and to shows an ellipses at the end of the width of the card so that it look aesthetically pleasing.
> scss Overflow TItle UX improvements

- .github/workflows/docker-image-rust-target-multi.yml
Add: `NODE_OPTIONS=--openssl-legacy-provider` due usage of node 18
> CI: fix docker nodejs ui build

- dim-database/src/user.rs
- dim-web/src/routes/auth.rs
- dim/src/core.rs
- dim/src/errors.rs
- dim/src/routes/user.rs
Continuing the Axum router migration work outlined here: https://github.com/Dusk-Labs/dim/issues/548
This PR migrates the `/api/v1/auth/whoami` route and implements Axum middleware for authentication in `core::with_auth`.
> Migrate whoami route to Axum router with authentication middleware

- dim-core/src/lib.rs
- dim-database/src/media.rs
- dim-database/src/mediafile.rs
- dim-database/src/season.rs
- dim-extern-api/src/tmdb/metadata_provider.rs
- dim-web/src/routes/auth.rs
- dim-web/src/routes/library.rs
- dim-web/src/routes/stream.rs
- dim-web/src/routes/tv.rs
I noticed some route failures that I had previously missed.
> Route fixes caught in more thorough testing

- dim-web/src/lib.rs
- dim-web/src/routes/websocket.rs
Resolves https://github.com/Dusk-Labs/dim/issues/590
I still don't fully understand why this was broken, but it seems that the `ctrl_event_processor` function couldn't match received events from a `tokio::sync::mpsc::Receiver` and only matched against an `tokio::sync::mpsc::UnboundedReceiver`.
> Fix WebSocket communication

- Cargo.lock
- dim-web/Cargo.toml
- dim-web/src/error.rs
- dim-web/src/lib.rs
- dim-web/src/middleware.rs
This change in the middleware supports both the Authorization header and Cookie methods of retrieving a valid auth token for a request.
---
CCCP reported this issue via Discord:
>I'm getting a 401 unauthorized error on the stream.ass when using subtitles, with the experimental SSA/ASS subtitles turned on (so the subtitles do not work)
the request header appears to contain the cookie (token=value) but not the Authorization=value header.
"GET /api/v1/stream/991698fc-1e7f-448c-876a-bc329d83e908/data/stream.ass HTTP/1.1
Host: ip:8001
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/119.0
Accept: /
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
DNT: 1
Connection: keep-alive
Referer: http://ip:8001/static/media/jassub-worker.555dbf2f1bc54cf00628.js …
> Authorization middleware supports cookie or authorization header
