Dusk-Labs/dim

- ui/src/Components/Banners/Banner.jsx
- ui/src/Components/CardList/CardPopup.jsx
- ui/src/Components/PlayButton.jsx
- ui/src/Pages/Media/MetaContent.jsx
> Show season and episode in play button

- ui/package.json
- ui/src/App.jsx
- ui/src/Components/Banners/Image.jsx
- ui/src/Components/Banners/Index.jsx
- ui/src/Components/CardList/CardPopup.jsx
- ui/src/Components/CardList/Image.jsx
- ui/src/Components/CardList/Index.jsx
- ui/src/Components/Sidebar/Libraries.jsx
- ui/src/Pages/Dashboard.jsx
- ui/src/Pages/Library/Index.jsx
- ui/src/Pages/Media/BannerImage.jsx
- ui/src/Pages/Media/CardImage.jsx
- ui/src/Pages/Media/MetaContent.jsx
- ui/src/Pages/VideoPlayer/Controls/SeekBar.jsx
- ui/src/Pages/VideoPlayer/Index.jsx
- ui/src/Routes/Private.jsx
- ui/src/actions/auth.js
- ui/src/actions/banner.js
- ui/src/actions/card.js
- ui/src/actions/fileBrowser.js
- ui/src/actions/library.js
- ui/src/actions/search.js
- ui/src/actions/user.js
Instead of using `window.host` for every API call.
> Add proxy to backend server

- README.md
> Round corners for screenshots

- src/database/src/user.rs
> add closing backticks to doc

- migrations/sqlite/2019-03-07-120346_openflix/up.sql
- src/build.rs
- src/core.rs
- src/database/src/progress.rs
- src/database/src/tv.rs
- src/main.rs
- src/routes/dashboard.rs
- src/routes/statik.rs
- src/routes/stream.rs
> Add recently viewed section

- src/scanners/tv_show.rs
> Issue EventNewCard for tv shows.

- Cargo.toml
- src/routes/statik.rs
> Fix release mode UI embed

- database/migrations/20210619211347_dim.sql
- database/src/library.rs
- dim/src/core.rs
- dim/src/lib.rs
- dim/src/scanners/mod.rs
- dim/src/scanners/scanner_daemon.rs
- dim/src/websocket.rs
- ui/public/index.html
- ui/src/Components/Misc/Button.scss
- ui/src/Modals/Index.scss
- ui/src/Modals/NewLibrary/DirSelection.jsx
- ui/src/Modals/NewLibrary/DirSelection.scss
- ui/src/Modals/NewLibrary/Index.jsx
- ui/src/Modals/NewLibrary/Index.scss
- ui/src/Modals/NewLibrary/MediaTypeSelection.jsx
- ui/src/Modals/NewLibrary/MediaTypeSelection.scss
- ui/src/Pages/Library/Index.jsx
- ui/src/Pages/Preferences/Index.jsx
- ui/src/Themes/Blind.js
- ui/src/Themes/Default.js
- ui/src/Themes/LightsOff.js
Other
- Adjusted some styling
- Fixes document title not changing when going to preferences page
> Select multiple folders when creating new library

- dim/src/core.rs
- dim/src/fetcher.rs
- dim/src/lib.rs
- dim/src/main.rs
- dim/src/scanners/movie.rs
- dim/src/scanners/tv_show.rs
> Refactor asset fetcher

- database/src/asset.rs
- database/src/episode.rs
- database/src/library.rs
- dim/Cargo.toml
- dim/src/core.rs
- dim/src/fetcher.rs
- dim/src/routes/library.rs
- dim/src/routes/media.rs
- dim/src/routes/settings.rs
- dim/src/routes/statik.rs
- dim/src/scanners/movie.rs
- dim/src/scanners/tv_show.rs
- events/src/lib.rs
Fixed a couple of bugs with the queue locking mechanism, and simplified the asset fetcher logic.
> Asset fetcher improvements

- Dockerfile
- README.md
- dim/Cargo.toml
- dim/src/core.rs
- dim/src/lib.rs
- dim/src/routes/library.rs
- dim/src/routes/stream.rs
- dim/src/scanners/movie.rs
- dim/src/scanners/scanner_daemon.rs
Clean up the filesystem notifier a bit. Fixed bug where inotify events werent being received when running inside docker.
Closes: #200
> Refactor fs notifier

- .github/workflows/rust.yml
- Dockerfile
This PR fixes the CI workflow for Rust failing. It also fixes the dockerfile failing to build.
> Fix CI and Dockerfile

- docker-compose-template.yml
Please **review the changelog** for `docker-compose-template.yml` and merge the changes.
The image name and the branch was incorrect in the main commit. Fixed it and tested it locally, works like a charm.
The future of **dim** looks very promising and the attention it got, just simple UI and no bloat, comes with support for Docker, absolutely like the development.
Keep up the good work ✨💖
By, @nooobcoder
Thank you.
@Dusk-Labs
> Fixed template docker-compose file

- dim/Cargo.toml
- dim/src/external/mod.rs
- dim/src/lib.rs
- dim/src/routes/library.rs
- dim/src/scanners/tmdb.rs
This PR defines a new interface that all metadata agents must follow.
> Update metadata agent interface

- ui/src/Pages/Preferences/Invites/Index.scss
- ui/src/Pages/Preferences/Invites/ManageInvites.jsx
This PR adds a couple of improvements to the UX of the invite token management tab in settings.
Closes: #473
> ui::invites: implement clipboard copy for invite token

- ui/src/Pages/Auth/Register.jsx
- ui/src/Pages/Preferences/Invites/ManageInvites.jsx
added feature that allows your copied invite token to be instantly added to the invite token input on he register page.
> Register improvements

- ui/src/Pages/Library/Index.scss
- ui/src/Pages/Library/MatchMedia/MediaTypeSelector.scss
The media matching UI didnt look good and was basically unuseable on lower resolution devices, this somewhat attempts to fix that.
> add media queries to improve the responsiveness of the media matching

- ui/src/Pages/VideoPlayer/Index.jsx
In this PR the issue was that i could not pause the Video when the user clicks on the screen. 
this new PR shows code that allows:
- you to toggle pause whenever you click the screen on the Movie/Series that you are watching.
> added feature that toggles player if the screen is clicked

- ui/src/Components/unfocusableButton.tsx
- ui/src/Pages/Preferences/Invites/ManageInvites.jsx
- ui/src/Pages/VideoPlayer/Controls/Actions/Fullscreen.jsx
- ui/src/Pages/VideoPlayer/Controls/Actions/NextVideo.jsx
- ui/src/Pages/VideoPlayer/Controls/Actions/PrevVideo.jsx
- ui/src/Pages/VideoPlayer/Controls/Actions/SeekBack.jsx
- ui/src/Pages/VideoPlayer/Controls/Actions/SeekForward.jsx
- ui/src/Pages/VideoPlayer/Controls/Actions/Settings.jsx
- ui/src/Pages/VideoPlayer/Controls/Actions/Subtitles.jsx
- ui/src/Pages/VideoPlayer/Controls/Actions/Volume.jsx
The button does not focus, meaning that when you press on settings, subtitles etc, you can still pause the video with your space-bar 
Closes: #477
> Fix button focus issues in media player

- Cargo.lock
- database/Cargo.toml
- dim/Cargo.toml
Closes #515
Closes #514 
Closes #521 
Closes #522
> Dependabot rollup

- Cargo.lock
- dim/Cargo.toml
- dim/benches/movie_scanner.rs
- dim/src/external/tmdb/cache_control.rs
- dim/src/external/tmdb/mod.rs
- dim/src/routes/stream.rs
- dim/src/scanner/daemon.rs
- dim/src/scanner/movie.rs
- dim/src/scanner/tests/mediafile.rs
- dim/src/scanner/tests/mod.rs
Also sorted the hunk of dependencies in cargo.toml in ascending order.
Had to update notify code to 5.0 this means we gotta test the new fs notification feature.
> chore(deps): update dependencies (rand, notify, govenor, uuid)

- database/src/asset.rs
- dim/src/routes/user.rs
> fix api throwing http 500 when uploading an avatar

- database/migrations/20230403182340_add-progress-unique-index.sql
> add media progress unique index

- ui/src/Components/AdvancedSearch/Index.tsx
- ui/src/Components/SimpleSearch.scss
- ui/src/Helpers/utils.ts
- ui/src/Pages/Library/Index.scss
- ui/src/Pages/Library/Index.tsx
- ui/src/Pages/Library/MatchMedia/Index.scss
- ui/src/Pages/Library/MatchMedia/Index.tsx
- ui/src/Pages/Library/MatchMedia/SearchResult.tsx
> Media matching fix

- CONTRIBUTING.md
> Correct urls, project name and license

- .github/workflows/Dockerfile.ci
- .github/workflows/docker-image-rust-target-multi.yml
- README.md
* Follow the main Dockerfile to node 18
* Change cache key to match the project name
* Add reference to `ghcr.io/dusk-labs/dim:master` for multi-arch image
> actions: CI update

- ui/package.json
"fixes" https://github.com/Dusk-Labs/dim/issues/550 ?
> swap node-sass for sass

- dim-web/src/routes/library.rs
- ui/src/Components/Sidebar/Libraries.jsx
- ui/src/Pages/Dashboard/Banners/Banner.tsx
- ui/src/Pages/Library/Dropdown.jsx
This PR resolves https://github.com/Dusk-Labs/dim/issues/330 and disallows non-admin users from adding or deleting libraries. This also removes the related frontend elements for non-admin users.
> Disallow creating or deleting a library if not owner role

- dim-core/src/routes/settings.rs
- dim-web/build.rs
- dim-web/src/routes/settings.rs
- ui/package.json
- ui/src/Components/Sidebar/Index.tsx
- ui/src/Components/Sidebar/Toggle.scss
- ui/src/Components/Sidebar/Toggle.tsx
This resolves https://github.com/Dusk-Labs/dim/issues/533
> Git tag and latest commit sha as version displayed in sidebar

- ui/src/Components/Sidebar/Libraries.jsx
- ui/src/reducers/library.js
Resolves https://github.com/Dusk-Labs/dim/issues/230
> Library sidebar uses unique React keys
